name: CI

on:
  push:
    branches:
      - 1.x
  pull_request:

jobs:
  latest:
    name: PHP ${{ matrix.php }} Symfony ${{ matrix.symfony }} ${{ matrix.composer-flags }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.1'
            symfony: "6.*"
          - php: '8.2'
            symfony: "*"
          - php: '8.3'
            symfony: "*"
          - php: '8.4'
            symfony: "*"
          - php: '8.1'
            composer-flags: "--prefer-lowest"
            symfony: "6.0.*"
          - php: '8.3'
            symfony: "6.*"
          - php: '8.3'
            symfony: "7.*"
          - php: '8.4'
            symfony: "8.*"
    env:
      SYMFONY_REQUIRE: ${{ matrix.symfony }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install composer dependencies
        run: |
          composer global require --no-update --no-scripts --no-plugins --no-ansi symfony/flex
          composer update --prefer-dist --no-interaction --no-progress --no-ansi ${{ matrix.composer-flags }}
          vendor/bin/simple-phpunit install

      - name: Execute tests
        run: |
          composer validate --strict --no-check-lock
          bin/rokka-cli
          vendor/bin/simple-phpunit -v
